site_name: AFT Blueprints
site_description: Account Factory for Terraform (AFT) Blueprints
copyright: Made with ❤️ by AWS Community.
repo_name: awslabs/aft-blueprints
repo_url: https://github.com/awslabs/aft-blueprints
docs_dir: "docs"

theme:
  name: material
  logo: static/aws-white-logo.png
  favicon: static/aws-colored-logo.png
  font:
    text: ember
    # code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: indigo
      accent: amber
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: indigo
      accent: amber
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
    - content.tooltips
    - content.tabs.link
    - content.code.copy
  highlightjs: true
  hljs_languages:
    - yaml
    - json
    - bash

plugins:
  - search
  - glightbox
  - minify:
      minify_html: true
  - social:
      cards: true
      cards_layout_options:
        font_family: Roboto

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
  - footnotes
