name: "Release Docs"

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - mkdocs.yaml
      - README.md
      - ".github/workflows/docbuild.yml"

permissions:
  contents: write
  id-token: write
  pages: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  PYTHON_VERSION: 3.12

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            mkdocs-material \
            mkdocs-glightbox \
            mkdocs-minify-plugin \
            mkdocs-material-extensions \
            mkdocs-awesome-pages-plugin \
            pillow cairosvg

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - run: mkdocs gh-deploy --force
